//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Languagedefineconfig_asset
    {
        public const string BundleName = "languagedefineconfig_asset";
        public const string LANGUAGEDEFINECONFIG = "LanguageDefineConfig";
    }
    public class Matview_rendertexture
    {
        public const string BundleName = "matview_rendertexture";
        public const string MATVIEW = "MatView";
    }
    public class Msyh_asset
    {
        public const string BundleName = "msyh_asset";
        public const string MSYH = "msyh";
    }
    public class Panel_design_prefab
    {
        public const string BundleName = "panel_design_prefab";
        public const string PANEL_DESIGN = "Panel_Design";
    }
    public class Panel_login_prefab
    {
        public const string BundleName = "panel_login_prefab";
        public const string PANEL_LOGIN = "Panel_Login";
    }
    public class Tg_image_prefab
    {
        public const string BundleName = "tg_image_prefab";
        public const string TG_IMAGE = "tg_image";
    }
    public class Uihomepanel_prefab
    {
        public const string BundleName = "uihomepanel_prefab";
        public const string UIHOMEPANEL = "UIHomePanel";
    }
}
